### ISSUE TITLE
Create a .NET back-end server

### ISSUE THREAD

**Issue by JaclyNolan** [midnight-animals/midnight-sahel-knowledge#19]
1. [x] create a backend service with .NET
2. [x] an api endpoint: GET /status, that returns 200 and a message “active”
3. [x] nosql database (mongodb?), with document, that has fields: id, title, content, author, createdAt
4. [x] think of what data schema your vocabulary app needs (or whatever app that was)
5. [x] define a CRUD endpoint for 3. and or 4.
6. [x] before you start, come up with an action plan, that you will follow, and can check of.
  i. adjust the action plan if needed during development 

7. [x] provide instructions for me on how i can run the service locally
8. [x] optional: dockerize the service
9. [x] use the latest version for all languages and libraries
10. [ ] bonus: create a react FE, that can communicate with the Be

goal: have a be service running, to which a fe can communicate to

[Main repo](https://github.com/midnight-animals/net-test-api)

**Comment by hiaux0** [comment]
changed priority to high
-> todo

**Comment by JaclyNolan** [comment]
> 5. define a CRUD endpoint for 3. and or 4.

Postman invite: (for convivence)
https://app.getpostman.com/join-team?invite_code=8a16b8df628dda334f43dc6414045686&target_code=35080673616635cd91283245951956d2

**Comment by JaclyNolan** [comment]
> use the latest version for all languages and libraries
I amma skip this for the time-being

**Comment by JaclyNolan** [comment]
> 7. provide instructions for me on how i can run the service locally

See README.md

**Comment by JaclyNolan** [comment]
> 10. bonus: create a react FE, that can communicate with the Be
Make this a new task
