### ISSUE TITLE
Tasks Tracking 26.2.24

### ISSUE THREAD

**Issue by JaclyNolan** [midnight-animals/midnight-sahel-knowledge#7]
Time spent: 0.33 hours

**Comment by JaclyNolan** [comment]
Understanding Guideline: 20 mins

**Comment by JaclyNolan** [comment]
https://github.com/midnight-animals/midnight-owling-private/issues/20 : 1.5 hours (trial)

**Comment by JaclyNolan** [comment]
#8 : 1 hour (trial)

**Comment by hiaux0** [comment]
@JaclyNolan 
you don't need to create a task tracking issue.
we can see from the board.
I will create a new board view, to extract the hours

![image](https://github.com/midnight-animals/midnight-sahel-knowledge/assets/30693990/5f83608c-49f1-4dbf-8525-d20c723e3abf)
