### ISSUE TITLE
Research Spiderum

### ISSUE THREAD

**Issue by JaclyNolan** [midnight-animals/midnight-sahel-knowledge#8]
Research https://spiderum.com/
- how many categories do they have?
- team size
- their success in actual numbers
- what can we learn from them

**Comment by JaclyNolan** [comment]
Action plan: 
* go to their site
* go through sub site
* collect info
* after these find potential interested points

**Comment by JaclyNolan** [comment]
@hiaux0 approved?

**Comment by JaclyNolan** [comment]
@hiaux0 sorry couldn't wait 😃 already done it
https://github.com/midnight-animals/midnight-owling-private/blob/524771d31c570ae005e383572a4a4f9d1c72575c/documents/spiderum.md

**Comment by hiaux0** [comment]
Missed this part

![image](https://github.com/midnight-animals/midnight-sahel-knowledge/assets/30693990/98cfea25-bacc-4a1b-9d39-4de71c185f2b)

**Comment by JaclyNolan** [comment]
To do:
* https://github.com/midnight-animals/midnight-owling-private/pull/21#discussion_r1509868163

**Comment by JaclyNolan** [comment]
+ 50 minutes getting actual posts
(takes extra time to code)

**Comment by JaclyNolan** [comment]
@hiaux0 Satisfactory?
https://github.com/midnight-animals/midnight-owling-private/blob/research/spiderum/documents/spiderum.md
